### ISSUE TITLE
Timeouts on CircleCI

### ISSUE THREAD

**Issue by cycomachead** [accesslint/accesslint-ci#17]
Hello,

I'm super excited to setup this up for a Rails app I'm working on, but  CircleCI always says the `rails server` command times out. In some sense, this makes sense because it's just running forever, but that's what the docs suggest...

Is there something that I'm missing?

**Comment by ckundo** [comment]
Hi @cycomachead, thanks for pointing this out, you'll need to daemonize the `rails server` command with the `-d` flag.

**Comment by cycomachead** [comment]
Thanks very much!
