### ISSUE TITLE
Trying to run behind auth

### ISSUE THREAD

**Issue by cycomachead** [accesslint/accesslint-ci#27]
I'm not sure what the best repo to put this issue under would be, but I'm happy to move it.

Essentially, I'd like to use AccessLint CI behind a login (since most of the functionality of this app requires accounts).

My thought process would be 
- have wget / curl get a cookie
- pass cookie to the accesslint-cli tool
- accesslint-cli passes the cookie to phantomjs

Does that make sense? This would touch 3 repos. I started working on this in a bit of a "see what works" way, but haven't gotten to the final step. I'm happy to submit PRs for what I have so far.

**Comment by ckundo** [comment]
@cycomachead thanks for the notes! Are you thinking pass an authentication token or basic auth via `curl`? This could work in a development or staging environment, or in a test environment with sample data, assuming authentication can be handled with token/basic auth. I'm not sure about scenarios with authentication via a web form. Did you have an idea for web form auth cookies?

Another approach is to conditionally inject https://github.com/accesslint/accesslint.js into your application template depending on the environment (non-production environments), then script interactions with a phantomjs browser and collect the output to stdout. 

If you're using Rails, https://github.com/accesslint/accesslint-rails helps with this.

**Comment by cycomachead** [comment]
Thanks for the response. 

I was trying to run behind a web-based login form. I've _almost_ got a hacky version working, though my circle.yml is ugly.

```
+    - bundle exec rails server -d -p 3000
 +    - wget --save-cookies cookies.txt --keep-session-cookies http://localhost:3000
 +    - token=$(grep -E 'action="/login".*="authenticity_token" value=".*" />' index.html | cut -d '"' -f 22)
 +    - encoded_value=$(python -c "import urllib; print urllib.quote('''$token''')")
 +    - wget --load-cookies cookies.txt --keep-session-cookies --save-cookies loggedin.txt --post-data="email=${LOGIN_EMAIL}&password=${LOGIN_PASSWORD}&authenticity_token=${encoded_value}" http://localhost:3000/login
 +    - gem install specific_install
 +    - gem specific_install -l https://github.com/cycomachead/accesslint-ci.git
 +    - accesslint-ci scan http://localhost:3000 cookies.txt
```

Obviously, this approach needs to be cleaner, but it seems possible. 

I'm currently looking into both accesslint-rails as well as the aXe-matchers gem. IMO a CI based linter and an rspec solution would be great _together_ because some pages might be required by law to be accessible (so rspec failures are appropriate), but CI is great to surface awareness in the rest of the app.

**Comment by ckundo** [comment]
@cycomachead this is helpful, I understand the approach. I'd like to take some time to consider where authentication should live. Will follow up with more thoughts.

**Comment by ckundo** [comment]
@cycomachead I wanted to followup and say I don't think we're ready to take on passing auth arguments to the CLI right away. For now, I'd recommend using accesslint.js per this comment https://github.com/accesslint/accesslint-ci/issues/27#issuecomment-258279075, or supporting basic auth in your app and authenticating that way.

**Comment by cycomachead** [comment]
@ckundo Thanks for the response! Totally understand. :) I'm definitely taking a look at accesslint.js.
