### ISSUE TITLE
Move the GitHub Project on this repo to be an organization-wide Project

### ISSUE THREAD

**Issue by tysongach** [accesslint/accesslint-ci#51]
https://github.com/blog/2272-introducing-projects-for-organizations

If we use an organization-wide GitHub project, we can pull in Issues from all of our AccessLint repos, which would be useful since we have lots of micro-services/repos.

**Comment by ckundo** [comment]
@tysongach should I pull in the card to the existing project at https://github.com/orgs/accesslint/projects/1? I also created https://github.com/orgs/accesslint/projects/2.

**Comment by tysongach** [comment]
Hrm…this raises an interesting question. Should there be separate be separate projects for accesslint-ci and accesslint.com? I was imagining them as going within one project so we can see everything together, since they are closely knit. Thoughts?
