### ISSUE TITLE
AccessLint posting duplicate errors

### ISSUE THREAD

**Issue by maya** [AccessLint/accesslint-ci#58]
AccessLint is posting errors twice as seen in https://github.com/18F/accessibility/issues/166 and https://github.com/18F/accessibility/pull/167#issuecomment-271734221. It should only post errors once.

Any idea why this is happening and how to resolve this?

**Comment by ckundo** [comment]
@maya I'm taking a look 👀

**Comment by maya** [comment]
@ckundo I'm not positive, but think it may be related to our search plugin processing files twice: https://github.com/18F/jekyll_pages_api_search/issues/37#issuecomment-271955021

**Comment by tysongach** [comment]
Closing, as we've taken AccessLint in a new direction. Check out our GitHub App: https://www.accesslint.com/
